# Generated by Django 3.2.4 on 2021-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountAPP', '0002_registereduser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='user_name',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='gender',
            field=models.CharField(default=23, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
