# Generated by Django 3.2.2 on 2021-06-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('profile_photo', models.ImageField(upload_to='booked profiles')),
                ('contact_number', models.CharField(max_length=12)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField(blank=True)),
                ('deasease', models.CharField(max_length=50)),
            ],
        ),
    ]
