# Generated by Django 3.2.4 on 2021-06-19 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAPP', '0003_auto_20210618_1025'),
        ('bookingAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dep_name',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='hospitalAPP.departments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='doc_name',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='hospitalAPP.doctors'),
            preserve_default=False,
        ),
    ]
