# Generated by Django 3.2.4 on 2021-06-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingAPP', '0002_auto_20210619_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dep_name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='doc_name',
            field=models.CharField(max_length=12),
        ),
    ]
