# Generated by Django 3.2.2 on 2021-06-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingAPP', '0003_auto_20210619_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='profile_photo',
            field=models.ImageField(upload_to='bookedprofiles'),
        ),
    ]
