# Generated by Django 3.2.2 on 2021-06-18 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('photos', models.ImageField(upload_to='Doctors')),
                ('numbers', models.CharField(max_length=12)),
                ('Departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalAPP.departments')),
            ],
        ),
    ]
