# Generated by Django 3.2.2 on 2021-06-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAPP', '0002_doctors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'ordering': ('Departments',), 'verbose_name': 'Docter', 'verbose_name_plural': 'Doctories'},
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='name',
            new_name='doc_name',
        ),
        migrations.AddField(
            model_name='doctors',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
