# Generated by Django 3.2.2 on 2021-06-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAPP', '0003_auto_20210618_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'ordering': ('departments',), 'verbose_name': 'Docter', 'verbose_name_plural': 'Doctories'},
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='Departments',
            new_name='departments',
        ),
    ]
